[build]
  command = "npm run build"
  publish = "dist"
  # functions = "netlify/functions" # uncomment if you add Netlify Functions

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
